version: '3.7'

services:
  sql:
    image: mysql:latest
    container_name: sql
    ports:
      - 3306:3306
    expose:
      - 3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    
